server:
  port: 8761
spring:
  profiles: s1
  application:
    name: cloud-service
eureka:
  client:
    serviceUrl: 
      defaultZone: http://sl:8762/eureka/
---
server: 
  port: 8762 
spring:
  profiles: s2
  application:
    name: cloud-service
eureka:
  client:
    serviceUrl: 
      defaultZone: http://sw:8761/eureka/
